In [ ]:
from data_preprocessing import create_df_tensors

# Exploration part

In [1]:
import pandas as pd

df = pd.read_csv("data/train_data.csv")

df.head()

,OPERATIONAL_DAY,TRAIN_NUMBER,OPERATION_TRAIN_NUMBER,OPERATION_TRAFFIC_CATEGORY_ABBREVIATION,COMMERCIAL_LINE_NUMBER_DESIGNATION,TRAIN_GROUP_TRAIN_CATEGORY_ABBREVIATION,TRAIN_GROUP_ROUTE,OPERATING_POINT_ABBREVIATION,EVENT_TYPE,EVENT_SERVED,PLAN_STOP_TYPE,OPERATION_PLANNED_TIMESTAMP,OPERATION_ACTUAL_TIMESTAMP,OPERATIONAL_PUNCTUAL,DAILY_PLAN_OPERATIONAL_DELAY_SEC,OPERATION_DAY_PERIOD_IDENTIFIER_COARSE,OPERATION_DAY_PERIOD_IDENTIFIER_FINE,OPERATION_TRAIN_RUN_SEQUENCE_NUMBER,PLAN_FORMATION_MAXIMAL_VELOCITY
0,2025-01-01,4,NaN,NaN,NaN,ICE,ZUE-BS-BAD-BEOS,LSN,departure,False,pass,NaN,NaN,0,NaN,NaN,NaN,NaN,200
1,2025-01-01,4,4.0,FV,NaN,ICE,ZUE-BS-BAD-BEOS,LANG,arrival,True,pass,2025-01-01 19:10:54.000 +0100,2025-01-01 19:17:11.000 +0100,0,377.0,NVZ,ABEND,11.0,200
2,2025-01-01,4,NaN,NaN,NaN,ICE,ZUE-BS-BAD-BEOS,HBTS,departure,False,pass,NaN,NaN,0,NaN,NaN,NaN,NaN,200
3,2025-01-01,4,4.0,FV,NaN,ICE,ZUE-BS-BAD-BEOS,EINF,departure,True,pass,2025-01-01 19:05:00.000 +0100,2025-01-01 19:11:03.000 +0100,0,363.0,NVZ,ABEND,5.0,200
4,2025-01-01,4,NaN,NaN,NaN,ICE,ZUE-BS-BAD-BEOS,HBTS,arrival,False,pass,NaN,NaN,0,NaN,NaN,NaN,NaN,200

In [4]:
small_df = df[:100]
small_df.head()
small_df.to_csv("data/train_data_small.csv")

small_df["OPERATING_POINT_ABBREVIATION"].unique()

array(['LSN', 'LANG', 'HBTS', 'EINF', 'SCHL', 'WOES', 'LB', 'MUOS',
       'GLZB', 'RU', 'GKD', 'ROHS', 'GEXI', 'SIS', 'MU', 'SCOE', 'GMT',
       'TK', 'AA', 'MELH', 'BSJS', 'LST', 'OLTU', 'DKW', 'BAD', 'LSSS',
       'BSVB', 'OLO', 'ZLST', 'BS', 'OTH', 'ZUE', 'SCOO', 'DU', 'MAEG',
       'BSNO', 'DK', 'DT', 'KLW', 'OLN', 'HBTN', 'SILB', 'ZAS', 'AAGB',
       'LSTN', 'GELN', 'IT', 'OLVL', 'AAO', 'GELL', 'ZHDB'], dtype=object)

# Create a map with all the stations

In [21]:
import pandas as pd
import folium

# Load your data
stations = pd.read_csv('data/train_stations.csv', delimiter=";", header=0)
train_data_small = pd.read_csv("data/train_data_small.csv", delimiter=",", header=0)

merged_df = stations.merge(train_data_small, on="OPERATING_POINT_ABBREVIATION")

merged_df = merged_df[["OPERATING_POINT_ABBREVIATION","BP_Name", "Latitude","Longitude"]].drop_duplicates(subset=["OPERATING_POINT_ABBREVIATION"])

import plotly.express as px

# Assuming 'stations' DataFrame has columns: 'latitude', 'longitude', and 'station_id'
fig = px.scatter_mapbox(
    merged_df,
    lat='Latitude',
    lon='Longitude',
    hover_name='BP_Name',  # or another identifier column
    zoom=10,
    height=600
)
fig.update_layout(
    mapbox_style="open-street-map",
    margin={"r":0,"t":0,"l":0,"b":0}
)
fig.show()

In [22]:
merged_df.head()

  OPERATING_POINT_ABBREVIATION            BP_Name   Latitude  Longitude
0                           AA             Aarau   47.391354   8.051268
2                         AAGB          Aarau GB   47.394524   8.066432
4                          AAO  Aarau Ost (Abzw)   47.395252   8.072316
6                          BAD      Basel Bad Bf   47.567301   7.606926
7                           BS         Basel SBB   47.547406   7.589569