This notebook preprocesses the different weather datasets

Table for the abbreviations used:

|Abbreviation|Meaning|
|---|---|
|tree200s0|Air temperature 2m|
|fkl010z1|gust peak (second gust)|
|fu3010z0|Wind velocity (10 minute mean km/h)|
|rre150z0|Precipation (10 minute mean)|
|htoauts0|Snow height at the moment|
|hto000d0|Snow height measured at 6am UTC|

## Weather data Neuchatel for Wind, Temperature, Precipation

In [1]:
import pandas as pd

# read in data
df = pd.read_csv("data\weather/neu_pre_temp_wind_sun.csv", delimiter=";", header=0)

cols_to_keep = ["station_abbr", "reference_timestamp", "date", "tre200s0", "fkl010z1", "fu3010z0", "rre150z0"]

#filter date
df['date'] = pd.to_datetime(df['reference_timestamp'], format="%d.%m.%Y %H:%M")
mask = (df['date'] >= '2025-01-01') & (df['date'] <= '2025-06-01')
filtered_df = df[mask]

filtered_df = filtered_df[cols_to_keep]
filtered_df["days"] = filtered_df['date'].dt.date
#filtered_df.head()

# Merge with snow data
neu_snow = pd.read_csv("data\weather/neu_snow.csv", delimiter=";", header=0)

cols_to_keep = ["station_abbr", "date", "reference_timestamp", "hto000d0"] # hto000d0 Schneehöhe um 6 UTC

neu_snow['date'] = pd.to_datetime(neu_snow['reference_timestamp'], format="%d.%m.%Y %H:%M")
mask_snow = (neu_snow['date'] >= '2025-01-01') & (neu_snow['date'] <= '2025-06-01')
filtered_df_snow = neu_snow[mask_snow]
filtered_neu_snow = filtered_df_snow[cols_to_keep]
filtered_neu_snow["days"] = filtered_neu_snow["date"].dt.date
#print(filtered_neu_snow.head())


merged_neu = pd.merge(filtered_df, filtered_neu_snow[['days', 'hto000d0']], on='days', how='left') 

#merged_neu[merged_neu["hto000d0"]>0.0]

C:\Users\carlo\AppData\Local\Temp\ipykernel_3608\3920795094.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_neu_snow["days"] = filtered_neu_snow["date"].dt.date

In [3]:
merged_neu.head()

,station_abbr,reference_timestamp,date,tre200s0,fkl010z1,fu3010z0,rre150z0,days,hto000d0
0,NEU,01.01.2025 00:00,2025-01-01 00:00:00,-1.0,3.0,6.8,0.0,2025-01-01,0.0
1,NEU,01.01.2025 00:10,2025-01-01 00:10:00,-0.9,3.0,6.5,0.0,2025-01-01,0.0
2,NEU,01.01.2025 00:20,2025-01-01 00:20:00,-0.6,2.7,6.1,0.0,2025-01-01,0.0
3,NEU,01.01.2025 00:30,2025-01-01 00:30:00,-1.5,4.2,9.4,0.0,2025-01-01,0.0
4,NEU,01.01.2025 00:40,2025-01-01 00:40:00,-1.2,4.5,10.4,0.0,2025-01-01,0.0

## Weather data for Grenchen Wind, Temperature, Precipation, Sunshine and Snow

In [ ]:
import pandas as pd

# read in data
df = pd.read_csv("data\weather/grenchen_pre_temp_wind_sun_snow.csv", delimiter=";", header=0)

cols_to_keep = ["station_abbr", "reference_timestamp", "tre200s0", "fkl010z1", "fu3010z0", "rre150z0", "htoauts0"]

#filter date
df['date'] = pd.to_datetime(df['reference_timestamp'], format="%d.%m.%Y %H:%M")
mask = (df['date'] >= '2025-01-01') & (df['date'] <= '2025-06-01')
filtered_df = df[mask]

filtered_df = filtered_df[cols_to_keep]
print(filtered_df.shape[0])
#filtered_df.head()

filtered_df[filtered_df["htoauts0"] > 0.0]

21745

,station_abbr,reference_timestamp,tre200s0,fkl010z1,fkl010z0,fu3010z0,rre150z0,htoauts0
278142,GRE,15.04.2025 13:00,16.8,3.5,1.9,6.8,0.0,2.0
279730,GRE,26.04.2025 13:40,15.4,9.8,6.3,22.7,0.0,2.0

In [30]:
# Data for snow in Neuchatel only daily

neu_snow = pd.read_csv("data\weather/neu_snow.csv", delimiter=";", header=0)

cols_to_keep = ["station_abbr","reference_timestamp", "hto000d0"] # hto000d0 Schneehöhe um 6 UTC

neu_snow['date'] = pd.to_datetime(neu_snow['reference_timestamp'], format="%d.%m.%Y %H:%M")
mask = (neu_snow['date'] >= '2025-01-01') & (neu_snow['date'] <= '2025-06-01')
filtered_df = neu_snow[mask]

filtered_neu_snow = filtered_df[cols_to_keep]
filtered_neu_snow[filtered_neu_snow["hto000d0"] > 0.0]

Empty DataFrame
Columns: [station_abbr, reference_timestamp, hto000d0]
Index: []